[package]
name = "sawtooth-raft"
version = "0.1.0"
authors = ["Intel Corporation"]
description = "Hyperledger Sawtooth Raft consensus engine"

[package.metadata.deb]
maintainer = "sawtooth"
depends = "$auto,rsyslog"
assets = [
    ["packaging/systemd/sawtooth-raft.service", "/lib/systemd/system/sawtooth-raft.service", "644"],
    ["packaging/systemd/sawtooth-raft", "/etc/default/sawtooth-raft", "644"],
    ["target/release/sawtooth-raft", "/usr/bin/sawtooth-raft", "755"]
]
maintainer-scripts = "packaging/ubuntu"

[dependencies]
clap = "2"
hex = "0.3"
log = "0.4"
log4rs = "0.8"
log4rs-syslog = "3.0"
protobuf = "2"
raft = "0.3.1"
sawtooth_sdk = { git = "https://github.com/hyperledger/sawtooth-core.git" }
serde_json = "1"

[patch.crates-io]
log4rs = { git = "https://github.com/ltseeley/log4rs", branch = "config-loading" }

[dev-dependencies]
tempdir = "0.3"
